networkPolicies:
  # -- Enable or disable the bundled network policies
  enabled: false
  # -- Configure which CIDRs istiod will be allowed to connect to
  # when accessing the kube-apiserver;
  # if none are specified, the chart will look up the default kubernetes
  # EndpointSlice and use the addresses found there
  controlPlaneCIDRs: []
  # -- A list of additional network policies to create
  # in the release namespace
  additionalPolicies: []

# -- A list of additional EnvoyFilters to create in the release namespace
additionalEnvoyFilters: []
# additionalEnvoyFilters:
#   - name: my-envoy-filter # required
#     labels: # optional
#       app: my-app
#     annotations: # optional
#       my-annotation: my-value
#     spec: # required
#       configPatches:
#         - applyTo: NETWORK_FILTER
#           match:
#             context: SIDECAR_INBOUND
#             listener:
#               portNumber: 8080
#               filterChain:
#                 filterType: NETWORK
#                 filterName: "envoy.filters.network.http_connection_manager"
#           patch:
#             operation: INSERT_BEFORE
#             value:
#               name: "envoy.filters.http.lua"
#               typed_config:
#                 "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
#                 inlineCode: |
#                   function envoy_on_request(request_handle)
#                     request_handle:headers():add("x-my-header", "my-value")
#                   end
#                   function envoy_on_response(response_handle)
#                     response_handle:headers():add("x-my-header", "my-value")
#                   end

monitoring:
  # -- Enable or disable the bundled monitoring components and
  # network policies
  enabled: true

authservice:
  enabled: false

mtls:
  # -- Set the mTLS mode for the istio-system namespace
  mode: STRICT

defaultSecurityHeaders:
  # -- Enable or disable the default security headers
  enabled: true

# -- Values to pass to [the upstream istiod chart](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml)
# @default -- Upstream chart values
upstream:
  env:
    ENABLE_NATIVE_SIDECARS: "true"

  meshConfig:
    accessLogFile: /dev/stdout
    meshMTLS:
      minProtocolVersion: TLSV1_2

  global:
    hub: registry1.dso.mil/ironbank/opensource/istio
    tag: 1.25.2
