{{- if .Values.networkPolicies.enabled }}
{{- $slice := lookup "discovery.k8s.io/v1" "EndpointSlice" "default" "kubernetes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apiserver-egress
spec:
  podSelector:
    matchLabels:
      app: istiod
  policyTypes:
  - Egress
  egress:
  - to:
    {{- if .Values.networkPolicies.controlPlaneCIDRs }}
    {{- range $cidr := .Values.networkPolicies.controlPlaneCIDRs }}
    - ipBlock:
        cidr: {{ $cidr }}
        {{- if eq $cidr "0.0.0.0/0" }}
        except:
          - 169.254.169.254/32 # Exclude IMDS
        {{- end }}
    {{- end }}
    {{- else }}
    {{- range $endpoint := $slice.endpoints }}
    {{- range $address := $endpoint.addresses }}
    - ipBlock:
        cidr: {{ $address }}/32
    {{- end }}
    {{- end }}
    {{- if $slice.ports }}
    ports:
    {{- range $port := $slice.ports }}
    - port: {{ $port.port }}
      protocol: {{ $port.protocol | upper }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
